-- Hyprland main config — Omarchy-style rice for Kali
-- Sources split config files; theme.lua is generated by `rice theme set`.

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GDK_BACKEND", "wayland,x11")

require("monitors")
require("looknfeel")
require("input")
require("bindings")
require("windowrules")
require("autostart")

-- theme.lua is generated by `rice theme set`; it's optional before the first run.
pcall(require, "theme")
