background {
    color = rgba(@bg@ff)
}

input-field {
    size = 220, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgba(@accent@ff)
    inner_color = rgba(@bg_alt@ff)
    font_color = rgba(@fg@ff)
    placeholder_text = password
    rounding = 10
    position = 0, 20
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(@fg@ff)
    font_size = 48
    position = 0, -80
    halign = center
    valign = center
}
